### ISSUE TITLE
Export declaration conflicts with exported declaration

### ISSUE THREAD

**Issue by andybeak** [akeating/typed-phoenix#1]
Hi,

Thanks for this package, it's really an awesome idea.  I can't get it working though, I'm new to the Typescript/Javascript world.

I've removed any reference to the javascript version of Phoenix from my systemjs config but when I try to run my app I get these errors:

```
typings/modules/phoenix/index.d.ts(5,3): error TS2484: Export declaration conflicts with exported declaration of 'Push'
typings/modules/phoenix/index.d.ts(7,3): error TS2484: Export declaration conflicts with exported declaration of 'Channel'
typings/modules/phoenix/index.d.ts(9,3): error TS2484: Export declaration conflicts with exported declaration of 'Socket'
typings/modules/phoenix/index.d.ts(10,3): error TS2484: Export declaration conflicts with exported declaration of 'LongPoll'
typings/modules/phoenix/index.d.ts(11,3): error TS2484: Export declaration conflicts with exported declaration of 'Presence'
```

**Comment by akeating** [comment]
@andybeak, this looks related to https://github.com/Microsoft/TypeScript/issues/9127, but is not something I've personally seen before. If you're looking to get rid of phoenix, simply remove the `typings` directory and any reference to `phoenix` in your `typings.json` file.
